### ISSUE TITLE
Build fails with Slurm 17.02

### ISSUE THREAD

**Issue by OleHolmNielsen** [fasrc/slurm_showq#8]
This used to work with Slurm 16.05, but now the make fails:

# make
make  all-am
make[1]: Entering directory `/root/slurm_showq-master'
g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT slurm_showq.o -MD -MP -MF .deps/slurm_showq.Tpo -c -o slurm_showq.o slurm_showq.cpp
In file included from slurm_showq.h:49:0,
                 from slurm_showq.cpp:45:
GetPot: In member function ‘const char* GetPot::__match_starting_string(const char*)’:
GetPot:1349:34: warning: converting ‘false’ to pointer type ‘const char*’ [-Wconversion-null]
     if( ! search_loop_f ) return false;
                                  ^
slurm_showq.cpp: In member function ‘void Slurm_Showq::query_running_jobs()’:
slurm_showq.cpp:54:22: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   char *delimiters = ",";
                      ^
slurm_showq.cpp:508:28: error: ‘WAIT_QOS_GRP_CPU_RUN’ was not declared in this scope
       job->state_reason != WAIT_QOS_GRP_CPU_RUN &&
                            ^
make[1]: *** [slurm_showq.o] Error 1
make[1]: Leaving directory `/root/slurm_showq-master'
make: *** [all] Error 2

**Comment by pedmon** [comment]
Interesting.  We just installed 17.02.6 here and when I built showq I got:

make  all-am
make[1]: Entering directory `/n/home_rc/pedmon/showq-slurm/current/slurm_showq'
g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT slurm_showq.o -MD -MP -MF .deps/slurm_showq.Tpo -c -o slurm_showq.o slurm_showq.cpp
slurm_showq.cpp: In member function ‘void Slurm_Showq::query_running_jobs()’:
slurm_showq.cpp:54: warning: deprecated conversion from string constant to ‘char*’
mv -f .deps/slurm_showq.Tpo .deps/slurm_showq.Po
g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp
mv -f .deps/main.Tpo .deps/main.Po
g++  -g -O2   -o showq slurm_showq.o main.o -lslurm 
make[1]: Leaving directory `/n/home_rc/pedmon/showq-slurm/current/slurm_showq'
[pedmon@holyitc01 slurm_showq]$ ls
aclocal.m4	config.h     config.status  GetPot    Makefile	   README	       slurm_showq.cpp	stamp-h1
autom4te.cache	config.h.in  configure	    main.cpp  Makefile.am  showq	       slurm_showq.h
build-aux	config.log   configure.ac   main.o    Makefile.in  showq.conf.example  slurm_showq.o
[pedmon@holyitc01 slurm_showq]$ showq
ACTIVE JOBS--------------------
JOBID     JOBNAME    USERNAME      STATE   CORE   REMAINING  STARTTIME
================================================================================

So it is working in my case.  So it clearly does work for 17.02.5.  What compiler are you using?  Perhaps that is the issue that is being hit.  In this case I used the default for CentOS6 which is gcc 4.4.7.

**Comment by OleHolmNielsen** [comment]
I'm on CentOS 7.3 with gcc 4.8.5.  I made a fresh git clone now, and the configure-make now works for me, so I think I'm good:

# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /root/slurm_showq/build-aux/missing --run aclocal-1.11 
/root/slurm_showq/build-aux/missing: line 52: aclocal-1.11: command not found
WARNING: `aclocal-1.11' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.ac'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.
 cd . && /bin/sh /root/slurm_showq/build-aux/missing --run automake-1.11 --foreign
/root/slurm_showq/build-aux/missing: line 52: automake-1.11: command not found
WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /root/slurm_showq/build-aux/missing --run autoconf
aclocal.m4:16: warning: this file was generated for autoconf 2.63.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically `autoreconf'.
/bin/sh ./config.status --recheck
running CONFIG_SHELL=/bin/sh /bin/sh ./configure --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking slurm/slurm.h usability... yes
checking slurm/slurm.h presence... yes
checking for slurm/slurm.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for uid_t in sys/types.h... yes
checking for uint32_t... yes
checking for strdup... yes
checking for strstr... yes
configure: creating ./config.status
 /bin/sh ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /root/slurm_showq/build-aux/missing --run autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
make  all-am
make[1]: Entering directory `/root/slurm_showq'
g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT slurm_showq.o -MD -MP -MF .deps/slurm_showq.Tpo -c -o slurm_showq.o slurm_showq.cpp
In file included from slurm_showq.h:49:0,
                 from slurm_showq.cpp:45:
GetPot: In member function ‘const char* GetPot::__match_starting_string(const char*)’:
GetPot:1349:34: warning: converting ‘false’ to pointer type ‘const char*’ [-Wconversion-null]
     if( ! search_loop_f ) return false;
                                  ^
slurm_showq.cpp: In member function ‘void Slurm_Showq::query_running_jobs()’:
slurm_showq.cpp:54:22: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   char *delimiters = ",";
                      ^
mv -f .deps/slurm_showq.Tpo .deps/slurm_showq.Po
g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp
In file included from slurm_showq.h:49:0,
                 from main.cpp:45:
GetPot: In member function ‘const char* GetPot::__match_starting_string(const char*)’:
GetPot:1349:34: warning: converting ‘false’ to pointer type ‘const char*’ [-Wconversion-null]
     if( ! search_loop_f ) return false;
                                  ^
mv -f .deps/main.Tpo .deps/main.Po
g++  -g -O2   -o showq slurm_showq.o main.o -lslurm 
make[1]: Leaving directory `/root/slurm_showq'
